"""What each Seoul Index card actually counts, and how that is checked.

One entry per card category (the `cat` every fact carries), written on
7 October 2026 after a day's audit found a dozen cards posting figures their
labels overstated. Each entry says:

  source           the publisher, service and fields the card reads
  counts           what the figures are, exactly, with the day's numbers
  checked_against  the independent figure it was set against, both numbers
  complete_fetch   how the code knows it read every row
  labels           whether the card's words claim exactly what the data holds;
                   anything still overclaiming is said here plainly
  verified         when this entry was last measured against live data
  checks           each source check: kind RECONCILE (against an independent
                   figure) or SHAPE (what the raw feed must look like), and
                   when it runs: 'build' (inside the harvester, every run;
                   a failure withholds the card and is logged), 'audit' (too
                   slow or costly per run; done by the monthly index-source-audit
                   task, which reads this file) or 'none' (nothing independent
                   exists, said why)

A stable, plausible figure is no evidence of a correct one: every wrong
figure on 7 October looked fine on its own. That is why no check here is a
plausibility range on the figure itself.

Nothing imports this at run time. test_seoul_index_provenance.py keeps it
whole: one entry per category the bot can emit, every field filled, and a
build check claimed only where the harvester really calls one.
"""

B, A, N = 'build', 'audit', 'none'
R, S = 'RECONCILE', 'SHAPE'


def c(kind, when, what):
    return {'kind': kind, 'when': when, 'what': what}


V = '2026-10-07'

PROVENANCE = {
    'crowd': {
        'source': 'Seoul 실시간 도시데이터 (KT estimate), data.seoul.go.kr citydata_ppltn/1/1/<AREA_NM>, one call per place',
        'counts': 'Our midpoint of KT’s published band (AREA_PPLTN_MIN to MAX; 강남역 22,000 to 24,000 gives 23,000) for people estimated inside the named place’s polygon at PPLTN_TIME, about 30 minutes behind the clock. Shares are KT’s PPLTN_RATE_20, FEMALE_PPLTN_RATE and NON_RESNT_PPLTN_RATE. Several polygons are wider than the label (“Gwanghwamun” is 광화문·덕수궁, “Jamsil” is 잠실 관광특구).',
        'checked_against': 'None independent: KT’s estimate is published only by Seoul. The fuller citydata endpoint repeats the same reading (same pipeline).',
        'complete_fetch': 'One row per place. A place that fails is skipped and the skip is printed.',
        'labels': 'Remaining: the figure is a midpoint we compute and the band is never shown; some place names are narrower than their polygons; “who don’t live there” reads NON_RESNT as non-residents of that area, not checked against Seoul’s spec.',
        'verified': V,
        'checks': [c(S, B, 'Each row is the place asked for, not a substituted reading, its band runs low to high, its eight age shares sum to 100 within 0.5 (99.8 to 100.1 measured), and male plus female and resident plus non-resident each to 100 within 0.2. All held on 26 of 26 places.'),
                   c(R, N, 'No second publisher of these estimates.')],
    },
    'spotlight': {
        'source': 'citydata_ppltn (as crowd) with its FCST_PPLTN 12-hour forecast, and the bot’s own crowd_history.jsonl via seoul_index_crowd_log.baseline()',
        'counts': '“Right now” is our midpoint at PPLTN_TIME; busiest and quietest hour ahead are midpoints of KT’s forecast bands for the next 12 hours; “Usual for a <weekday> at <h>” is the mean of our own logged midpoints for that place, weekday and hour over 3 or more days. Since 7 October 2026 the baseline and the live line are keyed on the reading’s own time, not the logger’s run time (which put the baseline about an hour early).',
        'checked_against': 'None independent.',
        'complete_fetch': 'One call; the baseline reads the whole local log.',
        'labels': 'HELD (HELD_CATS). The baseline fix has not yet been seen building a live card. Holidays are not left out of the baseline.',
        'verified': V,
        'checks': [c(S, B, 'The crowd row checks above, plus a forecast of exactly 12 hours, every one after the reading (12 of 12 on every place).'),
                   c(R, N, 'No second publisher.')],
    },
    'air': {
        'source': 'Seoul Research Institute of Public Health and Environment district monitors, data.seoul.go.kr ListAirQualityByDistrictService/1/25/',
        'counts': 'One urban monitor per district, the latest hour. Worst and cleanest are hourly PM2.5 (FPM); worst PM10 is PM, in µg/m³. The good and bad counts use CAI_GRD, the integrated index over PM, O3, NO2, CO and SO2, not PM grades. A monitor under maintenance (점검중) has no number and no grade.',
        'checked_against': 'RealtimeCityAir (same institute) matched exactly on 24 of 24 districts at 06:00 and 20:00 on 7 October 2026, but at 21:00 disagreed on all 24 under the same hour stamp (구로구 PM2.5 16 against 7) and on the grade in three. AirKorea (B552584) refuses our key (SERVICE_KEY_IS_NOT_REGISTERED_ERROR).',
        'complete_fetch': 'All 25 rows in one page.',
        'labels': 'HELD. The footnote prints PM2.5 and PM10 bands beside counts that are CAI grades, so a reader matching the two gets it wrong (서대문구 보통 with PM2.5 8). Which of the two Seoul services to trust is unsettled.',
        'verified': V,
        'checks': [c(S, B, '25 rows for 25 districts, one measurement hour no more than three hours old, PM10 never below PM2.5, every grade one of 좋음/보통/나쁨/매우나쁨.'),
                   c(R, A, 'Against RealtimeCityAir and, once the key is registered, AirKorea; not per run, because RealtimeCityAir agrees only some hours.')],
    },
    'transport': {
        'source': 'Seoul T-money card data: CardSubwayStatsNew/<YYYYMMDD>, CardBusStatisticsServiceNew/<YYYYMMDD>; Seoul membership through subwayStationMaster and busStopLocationXyInfo',
        'counts': 'Subway: card boardings that day at stations inside Seoul (within 300 m of a Seoul-registered bus stop, 석수 excepted, 자양 and 디엠시 aliased), summed across lines; Shinbundang and GTX-A are not in the feed. 3 October 2026: 4,846,269 at 307 stations. Bus: every row of Seoul-licensed buses, village buses included, at every stop including about 4.7 percent of boardings at Gyeonggi and Incheon stops; Gyeonggi- and Incheon-licensed buses are not in the feed even at Seoul stops. 3 October: 3,890,986.',
        'checked_against': 'Month sums of the same card data in another of Seoul’s tables: the daily subway boardings summed over August 2026 equal CardSubwayTime/202608 exactly (208,329,561), and September (216,589,218); alightings too. Bus: per route, history days summed equal CardBusTimeNew for September, 390 of 390 routes. Nothing outside the card system.',
        'complete_fetch': 'Subway: list_total_count read first, every row fetched (617 of 617). Bus: pages of 1,000 to list_total_count (40,250 of 40,250).',
        'labels': 'Subway line carries its scope. Remaining: “Bus boardings the same day” has no scope note (it includes Seoul buses’ boardings in Gyeonggi and leaves out Gyeonggi buses in Seoul).',
        'verified': V,
        'checks': [c(S, B, 'Subway: every row of the day arrived and is for that day, no unreadable count, no Shinbundang or GTX line; at most 3 rows unplaceable in or out of Seoul (1 measured).'),
                   c(S, B, 'Bus: every row arrived; stop ids are Seoul (1), Gyeonggi (2) or Incheon (9) and Seoul’s carry at least 90 percent of boardings (95.3 measured).'),
                   c(R, A, 'Month end: daily subway and bus sums against CardSubwayTime and CardBusTimeNew, exactly.')],
    },
    'stations': {
        'source': 'CardSubwayStatsNew (daily) with subwayStationMaster and busStopLocationXyInfo',
        'counts': 'Card boardings per station on one date, summed over its lines, Seoul stations only. Top two and the quietest of at least 10 boardings; the total is the transport subway total. 3 October 2026: 서울역 136,371; 홍대입구 122,571; 도림천 906.',
        'checked_against': 'As transport (month equality, exact). Membership against KOSTAT 2013 district polygons: all 307 pins inside Seoul.',
        'complete_fetch': 'As transport.',
        'labels': 'Footnote matches the data. Border stations are decided by distance, not address (복정 counted; 석수 excluded by name).',
        'verified': V,
        'checks': [c(S, B, 'The transport subway checks (same harvest).'),
                   c(R, A, 'Month-end equality, as transport; the in-Seoul station set compared with the month before, any change named.')],
    },
    'stationgap': {
        'source': 'CardSubwayStatsNew GTON_TNOPE and GTOFF_TNOPE, same membership as stations',
        'counts': 'For the Seoul station with the widest absolute difference between getting off and getting on, summed over its lines: alightings and boardings that day. 3 October 2026: 홍대입구, off 133,083, on 122,571.',
        'checked_against': 'Alightings month equality with CardSubwayTime GET_OFF, exact for August and September 2026.',
        'complete_fetch': 'As transport.',
        'labels': 'Remaining: “All lines combined” in STATIONGAP_NOTE_EN omits the Shinbundang and GTX-A proviso the stations footnote carries; it matters at 강남, 양재 and 신사.',
        'verified': V,
        'checks': [c(S, B, 'The transport subway checks, which require both counts readable on every row.'),
                   c(R, A, 'Alightings month equality.')],
    },
    'busroutes': {
        'source': 'CardBusStatisticsServiceNew per day, kept in bus_route_history.json',
        'counts': 'Seoul trunk (100 to 799) and branch (1000 to 7999) routes with 10 or more distinct stops taking a boarding: card boardings divided by those stops, all stops including Gyeonggi ones. The fourth line is the same measure over all eligible routes (118.4 on 3 October 2026).',
        'checked_against': 'Per-route month sums from the history equal CardBusTimeNew, 390 of 390 routes for September 2026.',
        'complete_fetch': 'As transport; the history freezes a day on first fetch.',
        'labels': 'Remaining: “Average per stop, all routes” is the eligible trunk and branch set, not all routes; “Number of stops” in the footnote is stops WITH A BOARDING, not the route’s stops.',
        'verified': V,
        'checks': [c(S, B, 'At least 300 eligible routes on the card’s day (326 or 327 on every day 26 August to 4 October 2026); fewer withholds this card alone.'),
                   c(R, A, 'History per-route month sums against CardBusTimeNew; a week-old day re-fetched against the stored one.')],
    },
    'busstops': {
        'source': 'CardBusStatisticsServiceNew summed per STOPS_ID, with busStopLocationXyInfo for coordinates and the stop count',
        'counts': 'Card boardings onto Seoul-licensed buses only, per stop id (one side of the road), Seoul-prefixed ids, one per English name. 3 October 2026: 지하철2호선강남역 11,969. The map’s stop count is every busStopLocationXyInfo row, 8 river-bus piers among them.',
        'checked_against': 'None independent at stop level. CardBusTimeNew carries monthly per-stop rows from the same system.',
        'complete_fetch': 'Bus as transport; coordinates paged to list_total_count (11,236).',
        'labels': 'Remaining: the busiest stop leaves out Gyeonggi and Incheon buses there (large at Gangnam and Seoul Station); the map’s “bus stops” count includes 8 river-bus piers.',
        'verified': V,
        'checks': [c(S, B, 'The transport bus checks (same harvest).'),
                   c(R, A, 'Month end: daily per-stop sums against CardBusTimeNew per stop.')],
    },
    'nightbus': {
        'source': 'bus_route_history.json, routes matching N plus digits',
        'counts': 'Card boardings on the calendar date on the 14 Seoul N routes, both directions summed. 98.6 percent of N-route boardings fall between midnight and 6 a.m., so since 7 October 2026 the dateline says “the early hours of” the date.',
        'checked_against': 'History month equality (September 2026, all 14 N routes exact).',
        'complete_fetch': 'As busroutes.',
        'labels': 'Accurate since the early-hours dateline.',
        'verified': V,
        'checks': [c(S, B, 'The transport bus checks.'),
                   c(R, A, 'History month equality; 14 N routes, each under one route number.')],
    },
    'busmovers': {
        'source': 'bus_route_history.json and Korean public holidays (date.nager.at, cached), with the fixed solar holidays added by date',
        'counts': 'Trunk and branch routes whose median over the previous 3 to 8 same weekdays is at least 1,000: the day’s boardings over that median, one biggest rise and one biggest fall. Holidays, including those on a weekend since 7 October 2026, are left out of both the day and the baselines.',
        'checked_against': 'History month equality. nager lists only the day off; KASI’s holiday service refuses our key.',
        'complete_fetch': 'As busroutes.',
        'labels': 'Note reads “usually over 1,000 boardings”, matching the median rule.',
        'verified': V,
        'checks': [c(S, B, 'The transport bus checks.'),
                   c(R, A, 'nager’s holidays against KASI getRestDeInfo once the key is registered.')],
    },
    'busweekend': {
        'source': 'bus_route_history.json and the holiday table',
        'counts': 'For the latest complete Monday-to-Sunday week with no holiday: each trunk and branch route’s mean weekend boardings over its mean weekday boardings (weekday mean at least 1,000).',
        'checked_against': 'History month equality.',
        'complete_fetch': 'As busroutes; all seven days needed.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(S, B, 'The transport bus checks.'),
                   c(R, A, 'As busmovers.')],
    },
    'rush': {
        'source': 'CardSubwayTime/<YYYYMM> (monthly, hourly)',
        'counts': 'Whole-month card boardings at 8 a.m. and 6 p.m. at one station NAME, summed over every line carrying that name. Not filtered to Seoul: 양평 would merge 5호선 (Seoul) with 중앙선 (Yangpyeong county). Since 7 October 2026 the month is the newest published, re-checked every run.',
        'checked_against': 'Month table against the daily feed, exact for August and September 2026.',
        'complete_fetch': 'Pages to list_total_count and refuses a short read; drops exact-duplicate rows (July 2026 served every row twice). A second, DIFFERENT row for one station and line is summed, deliberately (test_seoul_index_rush).',
        'labels': 'Remaining: a station name shared with one outside Seoul would be merged; none has been picked so far.',
        'verified': V,
        'checks': [c(S, B, 'Every row of the month read; a short read is a failed check, logged, and never falls back to an older month.'),
                   c(R, A, 'Month table against the daily feed summed; the picked station’s lines all inside Seoul.')],
    },
    'bike': {
        'source': 'Seoul Ttareungi live status, bikeList, and the operator’s station register tbCycleStationInfo',
        'counts': 'Over the stations in the live feed (2,738): bikes parked (30,393; QR bikes beside a full rack included), racks (32,955), stations with no bike (282).',
        'checked_against': 'The register’s HOLD_NUM over the same 2,738 stations: 32,955, exact, no station differing. The register lists 3,244; 506 are not in the live feed, reason not established.',
        'complete_fetch': 'Pages of 1,000 until a short page.',
        'labels': 'Remaining: “stations citywide” is stations in the live feed, not the 3,244 registered.',
        'verified': V,
        'checks': [c(R, B, 'Racks in the live feed equal the register’s over the same stations, exactly; every live station registered; none twice.'),
                   c(S, A, 'The register-only count (506), watched for a sharp move.')],
    },
    'traffic': {
        'source': 'TOPIS via data.seoul.go.kr xml/TrafficInfo/1/1/<link_id> and LinkInfo, links from traffic_links.json',
        'counts': 'Current processed speed on ONE standard link per road, one direction, 311 to 2,999 m long (“Gangnam-daero” is 한남대교남단 to 북단, 822 m). Decimal speeds are kept since 7 October 2026.',
        'checked_against': 'The link’s own length over the reading’s travel time: within 0.51 km/h on 11 of 11 links over three rounds (1.1 earlier the same day).',
        'complete_fetch': 'One call per link, three tries.',
        'labels': 'Remaining: a bare road name labels one short segment in one direction.',
        'verified': V,
        'checks': [c(R, B, 'Speed against length over travel time within 1.5 km/h, and the link still on the named road, every link every run.')],
    },
    'river': {
        'source': 'Seoul water-quality monitors WPOSInformationTime (WATT); air from KMA 초단기실황 nx 60 ny 127',
        'counts': 'Water temperature at 선유 (the Han) and the 탄천, 중랑천 and 안양천 at the newest hour with 선유 and 3 stations; the air at the same hour.',
        'checked_against': 'KMA grid 60/127 equals ASOS station 108 exactly on 3 of 3 hours checked. Water: no other publisher.',
        'complete_fetch': '120 newest rows, newest first.',
        'labels': 'Accurate. The feed’s 24:00 hour cannot make a card (strptime rejects it).',
        'verified': V,
        'checks': [c(R, A, 'The posted air reading against ASOS 108 for the same hour, the next day.'),
                   c(S, N, 'The vein already withholds without 선유, 3 stations and a KMA reading for the hour.')],
    },
    'level': {
        'source': 'HRFCO api.hrfco.go.kr waterlevel/list/10M/1018680 and waterlevel/info.json',
        'counts': 'Stage at the 서울시(잠수교) gauge against its four published tiers; silent below the first (3.9 m).',
        'checked_against': 'None independent. Same office: the 10-minute reading at the hour equals the hourly reading.',
        'complete_fetch': '13 slots in one call; the newest one or two are blank by design.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(S, B, 'On a run that gets past the gate: reading no more than 60 minutes old, tiers rising, the first equal to the gate.'),
                   c(R, A, '10-minute against hourly reading.')],
    },
    'price': {
        'source': 'Seoul 생필품 가격 survey, ListNecessariesPricesService (newest first)',
        'counts': 'One exact product, the shelf price with no note (discounts, multi-buys and imports left out), each market’s latest row in the newest round. Cheapest shop, dearest shop and two between.',
        'checked_against': 'None held: KAMIS and 참가격 need keys we do not hold.',
        'complete_fetch': 'Pages of 1,000 until a row predates the round; fails closed after 15 pages.',
        'labels': 'Products whose own fields disagree are skipped, not compared (see checks).',
        'verified': V,
        'checks': [c(S, B, 'The round reaches at least 22 districts (25 measured).'),
                   c(S, B, 'One variety per product, and no variety listing alternatives: 소고기(국산) “한우, 1등급, 1+등급 등심” is skipped.'),
                   c(S, B, 'The product name and the quantity field name the same unit: 고등어(염장) 1손 against QY 1마리 and 맥주 1캔 against QY 1병 are skipped.'),
                   c(R, N, 'No other publisher’s prices for the same markets.')],
    },
    'water': {
        'source': 'Seoul waterworks WoWcbsDayStatic, rows 1 to 300, newest first',
        'counts': '취수 (raw water drawn before treatment), m³ a day, at 5 of the 6 purification centers (암사, 강북, 뚝도, 구의, 영등포). 광암, the smallest (182,100 m³ on 5 October 2026), has no English name in WATER_SITES and is left out.',
        'checked_against': 'No other publisher. Same feed: transmission over intake for all six, 0.9776 to 0.9955 over 13 days.',
        'complete_fetch': '300 rows cover about 13 days; the newest day is whole.',
        'labels': 'Remaining: the selector rule says “each of Seoul’s purification centers” and an opener can imply the whole city; it is five of six.',
        'verified': V,
        'checks': [c(S, B, 'Newest first; the newest day whole (22 rows: 6 intake, 6 transmission, 10 supply) and no more than three days old; every center known or listed as left out (광암).'),
                   c(R, B, 'Transmission over intake between 0.96 and 1.01, which catches the two measures swapping.')],
    },
    'daynight': {
        'source': 'SPOP_DAILYSUM_JACHI_250 (자치구단위 서울생활인구 일별 집계표), rows 1 to 200',
        'counts': 'DAY_LVPOP_CO or NIGHT_LVPOP_CO per district: KT-modelled 생활인구, Korean nationals and foreigners. The portal does not define day or night.',
        'checked_against': 'Seoul’s hourly district series (three JACHI services summed): the daily table runs 1.087 to 1.104 times higher citywide and 0.96 to 1.30 by district (종로 by day 470,085 against the hourly peak 408,242). The hourly series lags about two months.',
        'complete_fetch': '26 rows a day; the newest day whole.',
        'labels': 'HELD: the figures are a different model from the city’s hourly series and the windows are undocumented.',
        'verified': V,
        'checks': [c(S, B, '25 districts and the 서울시 row; districts sum to the city row for day, night and all day (exact over ten days); each figure within its own daily minimum and maximum; each total its three parts within one person. NOT night <= total <= day: residential districts are fuller at night (104 rows in ten days).'),
                   c(R, A, 'Against the hourly series on its newest date, ratio 1.05 to 1.15.')],
    },
    'infant': {
        'source': 'KOSIS DT_1B04006, 서울 registered population by single year of age 0 to 5, year end',
        'counts': 'Korean nationals on Seoul’s resident register at year end, by age band, the newest year against 5 and 10 years earlier. Registered foreign children are not counted.',
        'checked_against': 'KOSIS DT_1B04005N (five-year bands, December): ages 0 to 4 summed equal its 0-4 band exactly for every year 2015 to 2025.',
        'complete_fetch': 'One call; a year missing any age is dropped and the card refuses without its three years.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(R, B, 'Ages 0 to 4 against the band table for each card year, exactly.')],
    },
    'library': {
        'source': 'SeoulLibraryMemberInfo; ratio denominator KOSIS DT_1B04005N, newest month',
        'counts': 'Registered members of 서울도서관 only, by AGE_RANGE band. The bands are KOREAN COUNTING AGE (band “10” is born 2008 to 2017 in 2026); the KOSIS denominator uses 만 age.',
        'checked_against': 'No other publisher of the membership. The age offset bends the “1 in N”: 만 10 to 19 is 717,871 against 679,090 born 2008 to 2017 (−5.4 percent); twenties −13 percent.',
        'complete_fetch': '95 of 95 rows, one page of 200.',
        'labels': 'Remaining: “Teens”, “20s” and the ratio’s “registered population that age” mix counting age with 만 age; the denominator should be rebuilt on matching birth years.',
        'verified': V,
        'checks': [c(S, B, 'Every row arrived, and every row’s birth year fits its band by counting age (95 of 95), so a switch to 만 age fails rather than shifting every decade.'),
                   c(R, N, 'No other publisher.')],
    },
    'complaint': {
        'source': 'SmartUncomfStatMonth (서울스마트불편신고 by year and month)',
        'counts': 'Reports filed through the 서울스마트불편신고 app and web channel only, per complete year (2025: 903,127). Not 120 다산콜 or other channels; not limited to residents.',
        'checked_against': 'SmartUncomfStatSector (same service, by field), summed per year: exact for every year 2012 to 2026 but 2025 (902,959, 0.019 percent apart).',
        'complete_fetch': '15 of 15 rows. The running year is excluded by an empty month.',
        'labels': 'Remaining: “Reports to Seoul” reads as all reports to the city by residents; it is one channel open to anyone.',
        'verified': V,
        'checks': [c(R, B, 'Each card year against the by-field table within 0.05 percent, every row of that table read.')],
    },
    'books': {
        'source': 'SeoulLibraryBookRentNumInfo via books_agg.json (seoul_index_books_harvest.py, monthly); window read from lib.seoul.go.kr/statistics/favorLoan',
        'counts': 'Checkouts at 서울도서관 only, rolling 60 days, summed by KDC class over the 3,000 records the feed serves, the publisher’s cut at 2 loans or more.',
        'checked_against': 'The library’s own TOP 100 page: 96 of 100 titles found; their loans 1,219 on the page against 1,232 in the API (+1.1 percent).',
        'complete_fetch': '3,000 of 3,000 rows.',
        'labels': 'Accurate (“3,000 most-borrowed” is loose only at the tie at 2 loans).',
        'verified': V,
        'checks': [c(S, B, 'In the harvest: every row arrived and parsed; the cut still at 2 loans or more; the window still stated on the library’s page; the top 3 titles on that page; under 5 percent unclassified.'),
                   c(R, A, 'TOP 100 loans on the page against the API, within 3 percent.')],
    },
    'spending': {
        'source': 'VwsmMegaSelngW (상권분석서비스 추정매출, 서울시 단위) via sales_agg.json (seoul_index_sales.py, monthly)',
        'counts': 'Estimated quarterly sales, citywide (card payments over a correction ratio), 15 curated industries of 63. Since 7 October 2026 the city’s own citywide estimate, not a sum over commercial districts (which ran 42 to 118 percent of it).',
        'checked_against': 'VwsmSignguSelngW (25 districts) summed per industry: equal to the citywide row to one part in a million for 1,383 of 1,386 industry-quarters, every industry in the newest four quarters.',
        'complete_fetch': 'Every row read (1,386); a quarter under 50 industries is refused.',
        'labels': 'Accurate (“Estimated sales, citywide”).',
        'verified': V,
        'checks': [c(S, B, 'The card refuses a cache not built from VwsmMegaSelngW.'),
                   c(R, B, 'In the monthly harvest: the newest quarter’s 63 industries equal their districts summed, sales and transactions, or nothing is written. Runs at harvest, not per post, because the district table is read whole (34 pages).')],
    },
    'avgbill': {
        'source': 'As spending',
        'counts': 'Estimated sales over estimated transactions, citywide, per quarter.',
        'checked_against': 'Both terms equal their district sums (see spending).',
        'complete_fetch': 'As spending.',
        'labels': 'Accurate; a ratio of two estimates.',
        'verified': V,
        'checks': [c(R, B, 'The spending harvest check, which covers transaction counts as well as sales.')],
    },
    'national': {
        'source': 'KOSIS DT_1B040A3 T20 (주민등록 총인구수) and DT_1B81A21 T1 (합계출산율), Korea and Seoul',
        'counts': 'Population: Korean nationals on the resident register at year end (2025: Seoul 9,299,548, Korea 51,117,378). Fertility: total fertility rate (2025: 0.799 and 0.632).',
        'checked_against': 'Population equals the monthly register’s December total exactly (2023 to 2025). The census with foreigners: Korea 51,817,499 (register 0.9865 of it), Seoul 9,315,066 (0.9983). Fertility: five times the summed age rates, within 0.0065.',
        'complete_fetch': 'One row per call.',
        'labels': 'Remaining: “People who live in South Korea / Seoul” is the register of nationals and misses about 700,000 foreign residents nationally.',
        'verified': V,
        'checks': [c(R, B, 'Population against the December register, exactly, Korea and Seoul.'),
                   c(R, B, 'Fertility against five times its seven age rates, within 0.01.'),
                   c(R, A, 'Register against the census including foreigners.')],
    },
    'world': {
        'source': 'OECD SDMX (OECD.CFE.EDS): DF_GREEN_AREA, DF_PT_ACCESS, DF_UHI, DF_DENSITY, nine functional urban areas',
        'counts': 'Green: m² per person of tree, shrub and grass cover in the URBAN CENTRE only, 2021. Transit: share of the FUA population within 5 minutes’ walk of a stop, 2023. Heat: summer-night land-surface temperature, urban minus non-urban. Density: FUA population over its area.',
        'checked_against': 'Density: implied Seoul FUA area 6,732 to 6,782 km² over 2020 to 2023 against the land-cover sum of 6,773. Green, transit, heat: none.',
        'complete_fetch': 'One CSV per measure; an empty answer is the OECD’s rate limit.',
        'labels': 'Remaining: the footnote’s “Metro areas” is wrong for green (urban centres); heat should say surface temperature.',
        'verified': V,
        'checks': [c(S, B, 'After the measure’s filter, one row per city and year, in the printed unit, for a functional urban area.'),
                   c(R, A, 'Density’s implied area within 1 percent of 6,750 km².')],
    },
    'nation': {
        'source': 'World Bank API (EN.POP.DNST, SP.DYN.TFRT.IN; 7 countries) and KOSIS for Seoul',
        'counts': 'Density: countries are World Bank population over LAND area; Seoul is registered nationals over 605.21 km². Fertility: total fertility rate.',
        'checked_against': 'Korea in both: fertility equal exactly (2022 to 2024); density, KOSIS’s register over the World Bank’s land area, 0.9925 to 1.0038 of the World Bank’s own.',
        'complete_fetch': '42 rows (7 countries × 6 years) in one page.',
        'labels': 'Bases differ (registered nationals against total population); under 1 percent at national level.',
        'verified': V,
        'checks': [c(R, B, 'Korea’s fertility equal in both sources; Korea’s density from KOSIS within 1.5 percent of the World Bank’s.')],
    },
    'property': {
        'source': '국토교통부 실거래가, RTMSDataSvcAptTrade and RTMSDataSvcAptRent, 25 districts, two months back; cached in molit_agg.json',
        'counts': 'Apartment sale filings with a contract date in the month, cancelled rows dropped, as of the harvest date (202608: 3,540). Leases split into jeonse and monthly rent.',
        'checked_against': 'Seoul’s own copy (tbLnOpendataRtmsV): 3,542 against 3,540 (202608), 5,843 against 5,841 (202607). Leases one sample, 0.962.',
        'complete_fetch': 'Pages to totalCount per district; any district failing fails the month.',
        'labels': 'Accurate; the cache is not refreshed, so late filings are missed.',
        'verified': V,
        'checks': [c(S, B, 'At harvest: each district’s rows exactly its totalCount, each for the district and month asked, the cancellation flag blank or O, sales in all 25 districts.'),
                   c(R, A, 'Citywide sales against Seoul’s copy, within 0.5 percent.')],
    },
    'weather': {
        'source': 'KMA ASOS daily, AsosDalyInfoService, station 108',
        'counts': 'The last full month and the same month 50 years earlier: hottest day (maxTa), wettest (sumRn), counts of days at 33°C or above, minimum at or above 25°C, maximum below 0°C; in summer, June to yesterday.',
        'checked_against': 'ASOS hourly: daily rain equals the hours summed exactly on 61 of 61 days; the daily maximum 0.1 to 1.1 above the hourly.',
        'complete_fetch': 'One page per span.',
        'labels': 'Remaining: “Nights never below 25°C” counts calendar days with the day’s minimum at or above 25°C, not KMA’s tropical night; “Days never above freezing” uses maximum below 0.',
        'verified': V,
        'checks': [c(S, B, 'One row per day of every span, each station 108 and inside the span.'),
                   c(R, A, 'Wettest and hottest day against the hourly readings.')],
    },
    'wxday': {
        'source': 'ASOS daily, yesterday’s row, station 108',
        'counts': 'High (maxTa), low (minTa), rain (sumRn; blank prints “None”), sunshine (sumSsHr), fresh-snow depth (ddMefs).',
        'checked_against': 'ASOS hourly, hours 00 to 23 (24:00 is not served until the day after): over 41 days, sunshine equal; rain from 01:00 never more than the total, none on a blank day; high 0 to 0.9 above, low 0 to 0.6 below.',
        'complete_fetch': 'One row.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(R, B, 'One row, station 108, yesterday; 24 hourly readings; sunshine equal; rain not exceeded; high and low within 1.5 of the hourly extremes.')],
    },
    'airport': {
        'source': 'Korea Airports Corporation, airport-transport-stats/info, 김포 row; KOSIS orgId 381 DT_920005_B001',
        'counts': 'Gimpo passengers (arrivals plus departures, every route) and flights in the month, the same month 20 years earlier, and the domestic/international split.',
        'checked_against': 'KOSIS for the same airport and month: equal on 48 of 48 airport-months and for August 2006.',
        'complete_fetch': 'numOfRows=100 against a totalCount of 14; all rows read.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(S, B, 'Every airport row read; passengers equal arrivals plus departures; domestic plus international equal the total.'),
                   c(R, B, 'Passengers and flights against KOSIS, exactly, for both months on the card.')],
    },
    'incheon': {
        'source': 'KOSIS orgId 381 DT_920005_B001 (인천); country line from 인천국제공항공사 operationPerformanceByRoute',
        'counts': 'Passengers (both directions, all flights; August 2026: 7,072,244), change from a year earlier, flights (38,624). Country line: every passenger (fare-paying, non-fare and transfer) on scheduled arrivals from that country’s airports.',
        'checked_against': 'KAC’s own feed (인천 row): equal on 24 of 24 months. Country line: all IIAC rows summed against KAC international arrivals, 0.9899 (one month only).',
        'complete_fetch': 'KOSIS one row per item per month; IIAC 411 of 411 rows.',
        'labels': 'Accurate since 6 October 2026.',
        'verified': V,
        'checks': [c(R, B, 'Passengers and flights against KAC’s 인천 row, exactly.'),
                   c(S, B, 'Every IIAC row for the month, a scheduled passenger arrival.'),
                   c(R, A, 'Country-line total against KAC arrivals, 0.97 to 1.00, provisional.')],
    },
    'railstations': {
        'source': '한국철도공사 mainLineStationPer (daily, per station)',
        'counts': 'Intercity boardings (KTX family, ITX, 새마을, 무궁화, 누리로) at the 8 Korail stations taken to be in Seoul, newest day. SRT and commuter trains not included.',
        'checked_against': 'None at station level. National monthly sums against mainLineDayOfWeekPer: 1.009 to 1.012.',
        'complete_fetch': 'Four pages of 5,000; the newest day is whole, the oldest is cut by the page and never stored.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(S, B, 'The card’s day is not the page-cut oldest day, holds at least 250 stations and all eight of Seoul’s.'),
                   c(R, A, 'National month sums against mainLineDayOfWeekPer, 1.000 to 1.025.')],
    },
    'seoulstation': {
        'source': 'mainLineStationPer (서울 row) and korail_station_history.json for the baseline',
        'counts': 'Boarded, got off and passengers on intercity Korail trains at 서울, newest day; typical is the median of the previous 8 same weekdays. Excludes AREX, Seoul Metro and Korail commuter trains.',
        'checked_against': 'None independent. History against feed: 서울 identical on 194 of 194 overlapping days. 27 history days cut at a page boundary were repaired on 7 October 2026 and a guard stops it recurring.',
        'complete_fetch': 'As railstations.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(S, B, 'The railstations day checks, and every baseline day a whole day (250 stations or more).')],
    },
    'railcommuter': {
        'source': '한국철도공사 wideRailloadStationPer (monthly), Seoul membership as stations; cached in railcommuter_cache.json',
        'counts': 'Monthly boardings at Korail commuter-line stations inside Seoul (석수 excluded since 7 October 2026, 디엠시 aliased to 디지털미디어시티). August 2026: 용산 1,620,814, 영등포 1,317,429, 서울 997,783.',
        'checked_against': 'Seoul’s card taps (CardSubwayTime) on the Korail line at stations only Korail serves: 0.990 to 0.997, March to August 2026. At shared stations Korail’s figure is 1.5 to 4.4 times the taps, reason not established: 서울 912,406 against 354,116.',
        'complete_fetch': 'One call of 5,000 against 3,696 rows.',
        'labels': 'OPEN: what Korail’s figure at 서울 counts is unresolved, and 서울 is often the third line. “All Seoul stations” means Korail commuter stations in Seoul.',
        'verified': V,
        'checks': [c(R, B, 'At harvest: Korail against Seoul’s card taps at 용산, 영등포, 회기, 개봉, 압구정로데오 and 구로, 0.98 to 1.00 each.'),
                   c(R, A, 'What the shared-station figures count, 서울 first.')],
    },
    'health': {
        'source': 'HIRA diseaseInfoService1 getDissByAreaStats1, medTp=1, year = this year − 2',
        'counts': 'Patients with that KCD code on health-insurance claims at institutions in Seoul (where the clinic is). Korean-medicine claims (medTp=2) are not included.',
        'checked_against': 'HIRA’s claims file (odcloud 15089587): 0.9995 to 1.0207 over 16 code-years.',
        'complete_fetch': 'One call per code, 17 regions.',
        'labels': 'Remaining: the footnote does not say Korean-medicine clinics are excluded; uses 2024 though 2025 is served.',
        'verified': V,
        'checks': [c(S, B, 'Each answer one row per region, all for the code asked, exactly one Seoul.'),
                   c(R, B, 'Seoul patients per code against the claims file, within 3 percent.')],
    },
    'healthcost': {
        'source': 'HIRA odcloud 15089587 (3단상병별 시도별), newest year',
        'counts': '요양급여비용총액 for Seoul and one code: total insured cost, insurer plus co-pay; the per-patient frame divides it by 환자수 in the same row.',
        'checked_against': 'diseaseInfoService1 for the same year, code and region: cost 0.9657 to 1.0099, patients 0.9613 to 1.0095, over 20 code-years.',
        'complete_fetch': 'One row per code (matchCount 1).',
        'labels': 'Remaining: “Insured treatment cost” could be read as insurer-paid only; the per-patient frame relies on the opener to say so.',
        'verified': V,
        'checks': [c(S, B, 'Each query matched one row, Seoul’s.'),
                   c(R, B, 'Cost and patients per code against the statistics service, within 5 percent.')],
    },
    'culture': {
        'source': 'MCST 문화기반시설총람, rgnCltrFcltExmnv1 clifMsmv1 and clifArglv1, newest edition with rows',
        'counts': 'Museums and galleries in the survey with a Seoul district code (136 and 50, 2023 figures), and the most-visited of each (annual visitors).',
        'checked_against': 'Visitors: KOSIS DT_150002_A052 (National Palace Museum) 883,599 for 2023, exact; also 2021 and 2022. Counts: KOSIS DT_110001_A034 says 124 and 48 for 2023; which edition matches which year is unsettled.',
        'complete_fetch': 'numOfRows 2,000 against 921 and 295.',
        'labels': 'Remaining: “Museums in Seoul” means facilities listed in the survey edition.',
        'verified': V,
        'checks': [c(S, B, 'Seoul district codes with Seoul addresses, one reference year, no facility twice.'),
                   c(R, B, 'National Palace Museum visitors against KOSIS, exactly.'),
                   c(R, A, 'Counts against DT_110001_A034 once the year alignment is settled.')],
    },
    'tourism': {
        'source': 'KCTI 관광자원통계, getPchrgTrrsrtVisitorList, 서울, newest month with rows',
        'counts': 'Monthly visitors per paid-admission site, free entrants included; foreigners as their own frame.',
        'checked_against': 'KOSIS TX_15002_A068: 경복궁 2025 equals the 12 months summed exactly; other palaces within 0.76 percent.',
        'complete_fetch': 'One page; but the newest month with rows can be partial.',
        'labels': 'HELD: since April 2026 the newest months carry Lotte’s rows only; the palaces have not reported.',
        'verified': V,
        'checks': [c(S, B, 'Every listed attraction reported for the same month a year earlier is reported now. Fails today on June 2026, correctly.'),
                   c(R, A, 'A full year against KOSIS TX_15002_A068.')],
    },
    'rescue': {
        'source': 'Animal and Plant Quarantine Agency, abandonmentPublic_v2, upr_cd 6110000, by rescue date',
        'counts': 'Rescue notices filed by Seoul district offices, rescued in the 7 days ending 3 days ago, every outcome; by species.',
        'checked_against': 'The register without the Seoul filter, Seoul offices picked by name: the identical 93 notices (28 September to 4 October 2026).',
        'complete_fetch': 'Paged to totalCount.',
        'labels': 'Accurate; late notices keep arriving after posting.',
        'verified': V,
        'checks': [c(S, B, 'Every notice from a Seoul office, none twice, each inside the window.'),
                   c(R, B, 'The unfiltered register’s Seoul notices, by name, the same set exactly.')],
    },
    'kopis': {
        'source': 'KOPIS prfstsArea, the 7 days ending yesterday, 서울 row',
        'counts': 'Productions with a showing, productions opening, showings, tickets sold net of cancellations, box office.',
        'checked_against': 'The 16 regions sum exactly to 합계 on every field; single days summed equal the week on showings, tickets and amount. The week’s figures settle upward after posting (1,990 showings at 07:00 and 1,992 at 21:00 on 7 October 2026 for the same week).',
        'complete_fetch': 'One answer, 21 area rows.',
        'labels': 'Remaining: whether box office is net of cancellations is unverified.',
        'verified': V,
        'checks': [c(R, B, 'Regions sum to 합계 exactly; tickets equal booked less cancelled on every row.'),
                   c(R, A, 'A week re-read 7 days later, to measure how far it settles.')],
    },
    'kepco': {
        'source': 'KEPCO bigdata.kepco.co.kr contractType.do, Seoul, newest month',
        'counts': 'Sums over 25 districts and contract types: kWh sold, won billed, and the residential and general shares.',
        'checked_against': 'KOSIS DT_31002_A006 (KEPCO’s own annual statistics): 2025 51,137,877 MWh against the 12 months summed, exact; 2024 likewise.',
        'complete_fetch': 'Refused under 150 rows (173 measured).',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(S, B, 'Every month read: all rows Seoul’s and for the month, 25 districts, each with the residential and general tariffs.'),
                   c(R, A, 'Last full year against KOSIS DT_31002_A006, to the MWh.')],
    },
    'kepcohist': {
        'source': 'contractType.do, newest month and the same month 20 years earlier',
        'counts': 'The same sums for both months; won are nominal.',
        'checked_against': 'KOSIS DT_31002_A006 2006 against that year’s 12 months: 16 MWh apart in 41.8 million.',
        'complete_fetch': '175 rows for July 2006.',
        'labels': 'Remaining: bills 20 years apart are nominal won and nothing says so.',
        'verified': V,
        'checks': [c(S, B, 'The kepco month checks on both months.'),
                   c(R, A, 'The earlier year against KOSIS.')],
    },
    'kepcohouse': {
        'source': 'KEPCO houseAve.do (가구평균), Seoul, newest month',
        'counts': 'KEPCO’s published average kWh and bill per household by district; the card shows the ends. KEPCO’s household count is about 10 percent above registered households (4,968,451 against 4,522,718).',
        'checked_against': 'The same month’s residential sales: averages weighted up are 0.905 to 0.932 of them over 31 months, unexplained.',
        'complete_fetch': 'Exactly 25 rows.',
        'labels': 'Remaining: “Average per household” is KEPCO’s wording; its household count is not registered households.',
        'verified': V,
        'checks': [c(S, B, '25 rows, 25 districts, Seoul, the month asked.'),
                   c(R, B, 'Averages weighted up against residential sales, 0.89 to 0.945.')],
    },
    'kepcohk': {
        'source': 'Seoul: 12 months of contractType.do and houseAve.do, KOSIS registered population. Hong Kong: hand constants (C&SD table 4.1, C&SD population and households, CLP and HK Electric reports)',
        'counts': 'Per person and per household, a year each side.',
        'checked_against': 'HK households match C&SD 130-06102. HK population revised by C&SD to 7,508,700 (the constant updated from the provisional 7,510,800 on 7 October 2026).',
        'complete_fetch': 'All 12 months or no card.',
        'labels': 'Remaining: Seoul’s per-person divisor leaves out registered foreigners while Hong Kong’s includes everyone; Seoul’s households are KEPCO’s count.',
        'verified': V,
        'checks': [c(S, B, 'Every month through the kepco and kepcohouse checks.'),
                   c(R, B, 'Hong Kong households and population against C&SD’s own tables, within 0.1 percent.'),
                   c(R, A, 'The energy figures, which have no API, against their annual reports.')],
    },
    'boxoffice': {
        'source': 'KOBIS searchDailyBoxOfficeList, wideAreaCd 0105001 (Seoul)',
        'counts': 'Admissions on Seoul screens for the day, the top 4 of KOBIS’s Seoul top 10.',
        'checked_against': 'Running totals: today’s less yesterday’s equal the day, 72 of 72 film-days; the weekly list equals 7 dailies; every Seoul figure below the national.',
        'complete_fetch': 'The top 10 is the endpoint’s fixed cut.',
        'labels': 'Accurate.',
        'verified': V,
        'checks': [c(S, B, '10 rows in order of admissions.'),
                   c(R, B, 'Running totals against the day before, exactly; every film’s Seoul figure below its national one.')],
    },
    'boxhist': {
        'source': 'KOBIS daily Seoul list, rank 1 on the day and the same date 5 and 10 years back',
        'counts': 'Seoul screens showing the day’s most-watched film.',
        'checked_against': 'None independent; Seoul screens never above national.',
        'complete_fetch': 'One row a year, three or none.',
        'labels': 'The own-vein card relies on the opener to say “screens for the most-watched film”.',
        'verified': V,
        'checks': [c(S, B, 'Each year’s first row is the most watched.'),
                   c(R, A, 'Seoul screens against the national figure for the same film and date.')],
    },
    'infra': {
        'source': 'list_total_count of TbPublicWifiInfo, SeoulPublicLibraryInfo, SeoulLibraryBookSearchInfo, SearchParkInfoService, busStopLocationXyInfo, culturalEventInfo, culturalSpaceInfo, GetParkInfo',
        'counts': 'Row counts, not distinct things: Wi-Fi 26,286 access points at 12,236 sites; car parks 2,190 rows for 851 lots; events 19,581 listings back to 2014 (394 not yet ended); holdings are bibliographic records.',
        'checked_against': 'None from another publisher; distinct-key counts within each feed as above.',
        'complete_fetch': 'Reads list_total_count only.',
        'labels': 'HELD: car parks, events, Wi-Fi (“the city runs”: most are districts’ or the ministry’s) and catalog items all overclaim.',
        'verified': V,
        'checks': [c(S, N, 'The fix is to count distinct keys, which the release will do; a check on a bare total can only restate it.')],
    },
}
